/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.samuel

import com.samuel.adapters.JiraRestApiClient
import com.samuel.adapters.TogglRestApiClient
import com.samuel.core.use_cases.GetTogglSummaryReport
import com.samuel.core.use_cases.GetTogglSummaryReportForPastWeek
import com.samuel.core.use_cases.MapTogglTimeRecordsToJIRAWorklogEntries
import com.samuel.core.use_cases.PostWorklogEntriesToJira
import io.ktor.client.*
import java.io.File
import kotlin.system.exitProcess

val VALID_COMMANDS = listOf("display", "post")

fun main(args: Array<String>) {
    if (args.isEmpty() || !VALID_COMMANDS.contains(args[0])) {
        throw Exception("Usage: toggle-to-jira <display | post> [weeksOffsetFromToday]")
    }

    val weeksOffsetFromToday = if (args.size > 1) args[1].toInt() else 1

    val props = TogglToJiraProperties.loadFromFile(File("config.properties").absoluteFile)
    val getPastWeek = GetTogglSummaryReportForPastWeek(
        getTogglSummaryReport = GetTogglSummaryReport(
            TogglRestApiClient(
                client = HttpClient(),
                apiToken = props.togglApiToken,
                userAgent = props.togglUserAgent,
                projectIds = props.togglProjectIds,
                workspaceId = props.togglWorkspaceId
            )
        )
    )

    if (args[0] == "display") {
        println(DisplayController(getPastWeek).display(weeksOffsetFromToday))
    } else if (args[0] == "post") {
        val mapToJira = MapTogglTimeRecordsToJIRAWorklogEntries()
        val postToJira = PostWorklogEntriesToJira(
            jiraClient = JiraRestApiClient(
                client = HttpClient(),
                apiToken = props.jiraApiToken,
                username = props.jiraUsername,
                jiraBaseUrl = props.jiraBaseUrl
            )
        )

        PostController(getPastWeek, mapToJira, postToJira).post(weeksOffsetFromToday)
    }

    exitProcess(0)
}
